//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.requestadjustmentdata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.requestadjustmentdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.requestadjustmentdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TTNPosType }
     * 
     */
    public TTNPosType createTTNPosType() {
        return new TTNPosType();
    }

    /**
     * Create an instance of {@link ActWOSPosType }
     * 
     */
    public ActWOSPosType createActWOSPosType() {
        return new ActWOSPosType();
    }

    /**
     * Create an instance of {@link ActCOType }
     * 
     */
    public ActCOType createActCOType() {
        return new ActCOType();
    }

    /**
     * Create an instance of {@link ActWOSType }
     * 
     */
    public ActWOSType createActWOSType() {
        return new ActWOSType();
    }

    /**
     * Create an instance of {@link ReportProducedType }
     * 
     */
    public ReportProducedType createReportProducedType() {
        return new ReportProducedType();
    }

    /**
     * Create an instance of {@link ActTTNType }
     * 
     */
    public ActTTNType createActTTNType() {
        return new ActTTNType();
    }

    /**
     * Create an instance of {@link ActWOPosType }
     * 
     */
    public ActWOPosType createActWOPosType() {
        return new ActWOPosType();
    }

    /**
     * Create an instance of {@link RouteType }
     * 
     */
    public RouteType createRouteType() {
        return new RouteType();
    }

    /**
     * Create an instance of {@link ReportImportedType }
     * 
     */
    public ReportImportedType createReportImportedType() {
        return new ReportImportedType();
    }

    /**
     * Create an instance of {@link RequestAdjustmentData }
     * 
     */
    public RequestAdjustmentData createRequestAdjustmentData() {
        return new RequestAdjustmentData();
    }

    /**
     * Create an instance of {@link RequestAdjustmentPositionType }
     * 
     */
    public RequestAdjustmentPositionType createRequestAdjustmentPositionType() {
        return new RequestAdjustmentPositionType();
    }

    /**
     * Create an instance of {@link ActWOType }
     * 
     */
    public ActWOType createActWOType() {
        return new ActWOType();
    }

    /**
     * Create an instance of {@link TTNType }
     * 
     */
    public TTNType createTTNType() {
        return new TTNType();
    }

}
