//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.requestadjustmentdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * “ип документа
 * 
 * <p>Java class for RequestAdjustmentPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestAdjustmentPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TTN" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}TTNType"/>
 *         &lt;element name="TTNPos" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}TTNPosType"/>
 *         &lt;element name="ReportProduced" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ReportProducedType"/>
 *         &lt;element name="ReportImported" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ReportImportedType"/>
 *         &lt;element name="ActWO" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ActWOType"/>
 *         &lt;element name="ActWOPos" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ActWOPosType"/>
 *         &lt;element name="ActWOS" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ActWOSType"/>
 *         &lt;element name="ActWOSPos" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ActWOSPosType"/>
 *         &lt;element name="ActCO" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ActCOType"/>
 *         &lt;element name="ActTTN" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}ActTTNType"/>
 *         &lt;element name="Route" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}RouteType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestAdjustmentPositionType", propOrder = {
    "ttn",
    "ttnPos",
    "reportProduced",
    "reportImported",
    "actWO",
    "actWOPos",
    "actWOS",
    "actWOSPos",
    "actCO",
    "actTTN",
    "route"
})
public class RequestAdjustmentPositionType {

    @XmlElement(name = "TTN")
    protected TTNType ttn;
    @XmlElement(name = "TTNPos")
    protected TTNPosType ttnPos;
    @XmlElement(name = "ReportProduced")
    protected ReportProducedType reportProduced;
    @XmlElement(name = "ReportImported")
    protected ReportImportedType reportImported;
    @XmlElement(name = "ActWO")
    protected ActWOType actWO;
    @XmlElement(name = "ActWOPos")
    protected ActWOPosType actWOPos;
    @XmlElement(name = "ActWOS")
    protected ActWOSType actWOS;
    @XmlElement(name = "ActWOSPos")
    protected ActWOSPosType actWOSPos;
    @XmlElement(name = "ActCO")
    protected ActCOType actCO;
    @XmlElement(name = "ActTTN")
    protected ActTTNType actTTN;
    @XmlElement(name = "Route")
    protected RouteType route;

    /**
     * Gets the value of the ttn property.
     * 
     * @return
     *     possible object is
     *     {@link TTNType }
     *     
     */
    public TTNType getTTN() {
        return ttn;
    }

    /**
     * Sets the value of the ttn property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTNType }
     *     
     */
    public void setTTN(TTNType value) {
        this.ttn = value;
    }

    /**
     * Gets the value of the ttnPos property.
     * 
     * @return
     *     possible object is
     *     {@link TTNPosType }
     *     
     */
    public TTNPosType getTTNPos() {
        return ttnPos;
    }

    /**
     * Sets the value of the ttnPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTNPosType }
     *     
     */
    public void setTTNPos(TTNPosType value) {
        this.ttnPos = value;
    }

    /**
     * Gets the value of the reportProduced property.
     * 
     * @return
     *     possible object is
     *     {@link ReportProducedType }
     *     
     */
    public ReportProducedType getReportProduced() {
        return reportProduced;
    }

    /**
     * Sets the value of the reportProduced property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportProducedType }
     *     
     */
    public void setReportProduced(ReportProducedType value) {
        this.reportProduced = value;
    }

    /**
     * Gets the value of the reportImported property.
     * 
     * @return
     *     possible object is
     *     {@link ReportImportedType }
     *     
     */
    public ReportImportedType getReportImported() {
        return reportImported;
    }

    /**
     * Sets the value of the reportImported property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportImportedType }
     *     
     */
    public void setReportImported(ReportImportedType value) {
        this.reportImported = value;
    }

    /**
     * Gets the value of the actWO property.
     * 
     * @return
     *     possible object is
     *     {@link ActWOType }
     *     
     */
    public ActWOType getActWO() {
        return actWO;
    }

    /**
     * Sets the value of the actWO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWOType }
     *     
     */
    public void setActWO(ActWOType value) {
        this.actWO = value;
    }

    /**
     * Gets the value of the actWOPos property.
     * 
     * @return
     *     possible object is
     *     {@link ActWOPosType }
     *     
     */
    public ActWOPosType getActWOPos() {
        return actWOPos;
    }

    /**
     * Sets the value of the actWOPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWOPosType }
     *     
     */
    public void setActWOPos(ActWOPosType value) {
        this.actWOPos = value;
    }

    /**
     * Gets the value of the actWOS property.
     * 
     * @return
     *     possible object is
     *     {@link ActWOSType }
     *     
     */
    public ActWOSType getActWOS() {
        return actWOS;
    }

    /**
     * Sets the value of the actWOS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWOSType }
     *     
     */
    public void setActWOS(ActWOSType value) {
        this.actWOS = value;
    }

    /**
     * Gets the value of the actWOSPos property.
     * 
     * @return
     *     possible object is
     *     {@link ActWOSPosType }
     *     
     */
    public ActWOSPosType getActWOSPos() {
        return actWOSPos;
    }

    /**
     * Sets the value of the actWOSPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActWOSPosType }
     *     
     */
    public void setActWOSPos(ActWOSPosType value) {
        this.actWOSPos = value;
    }

    /**
     * Gets the value of the actCO property.
     * 
     * @return
     *     possible object is
     *     {@link ActCOType }
     *     
     */
    public ActCOType getActCO() {
        return actCO;
    }

    /**
     * Sets the value of the actCO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActCOType }
     *     
     */
    public void setActCO(ActCOType value) {
        this.actCO = value;
    }

    /**
     * Gets the value of the actTTN property.
     * 
     * @return
     *     possible object is
     *     {@link ActTTNType }
     *     
     */
    public ActTTNType getActTTN() {
        return actTTN;
    }

    /**
     * Sets the value of the actTTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActTTNType }
     *     
     */
    public void setActTTN(ActTTNType value) {
        this.actTTN = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link RouteType }
     *     
     */
    public RouteType getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteType }
     *     
     */
    public void setRoute(RouteType value) {
        this.route = value;
    }

}
