//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.requestadjustmentdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Транспортная накладная
 * 
 * <p>Java class for RouteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="RegId" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="Date" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *         &lt;element name="TRAN_TYPE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="410"/>
 *               &lt;enumeration value="411"/>
 *               &lt;enumeration value="412"/>
 *               &lt;enumeration value="413"/>
 *               &lt;enumeration value="419"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAN_COMPANY" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255" minOccurs="0"/>
 *         &lt;element name="TRAN_CAR" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255"/>
 *         &lt;element name="TRAN_TRAILER" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255" minOccurs="0"/>
 *         &lt;element name="TRAN_CUSTOMER" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255" minOccurs="0"/>
 *         &lt;element name="TRAN_DRIVER" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255" minOccurs="0"/>
 *         &lt;element name="TRAN_LOADPOINT" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString"/>
 *         &lt;element name="TRAN_UNLOADPOINT" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString"/>
 *         &lt;element name="TRAN_REDIRECT" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255" minOccurs="0"/>
 *         &lt;element name="TRAN_FORWARDER" type="{http://fsrar.ru/WEGAIS/RequestAdjustmentData}Field255" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteType", propOrder = {

})
public class RouteType {

    @XmlElement(name = "RegId", required = true)
    protected String regId;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "TRAN_TYPE", required = true)
    protected String trantype;
    @XmlElement(name = "TRAN_COMPANY")
    protected String trancompany;
    @XmlElement(name = "TRAN_CAR", required = true)
    protected String trancar;
    @XmlElement(name = "TRAN_TRAILER")
    protected String trantrailer;
    @XmlElement(name = "TRAN_CUSTOMER")
    protected String trancustomer;
    @XmlElement(name = "TRAN_DRIVER")
    protected String trandriver;
    @XmlElement(name = "TRAN_LOADPOINT", required = true)
    protected String tranloadpoint;
    @XmlElement(name = "TRAN_UNLOADPOINT", required = true)
    protected String tranunloadpoint;
    @XmlElement(name = "TRAN_REDIRECT")
    protected String tranredirect;
    @XmlElement(name = "TRAN_FORWARDER")
    protected String tranforwarder;

    /**
     * Gets the value of the regId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegId() {
        return regId;
    }

    /**
     * Sets the value of the regId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegId(String value) {
        this.regId = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the trantype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANTYPE() {
        return trantype;
    }

    /**
     * Sets the value of the trantype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANTYPE(String value) {
        this.trantype = value;
    }

    /**
     * Gets the value of the trancompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANCOMPANY() {
        return trancompany;
    }

    /**
     * Sets the value of the trancompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANCOMPANY(String value) {
        this.trancompany = value;
    }

    /**
     * Gets the value of the trancar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANCAR() {
        return trancar;
    }

    /**
     * Sets the value of the trancar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANCAR(String value) {
        this.trancar = value;
    }

    /**
     * Gets the value of the trantrailer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANTRAILER() {
        return trantrailer;
    }

    /**
     * Sets the value of the trantrailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANTRAILER(String value) {
        this.trantrailer = value;
    }

    /**
     * Gets the value of the trancustomer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANCUSTOMER() {
        return trancustomer;
    }

    /**
     * Sets the value of the trancustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANCUSTOMER(String value) {
        this.trancustomer = value;
    }

    /**
     * Gets the value of the trandriver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANDRIVER() {
        return trandriver;
    }

    /**
     * Sets the value of the trandriver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANDRIVER(String value) {
        this.trandriver = value;
    }

    /**
     * Gets the value of the tranloadpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANLOADPOINT() {
        return tranloadpoint;
    }

    /**
     * Sets the value of the tranloadpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANLOADPOINT(String value) {
        this.tranloadpoint = value;
    }

    /**
     * Gets the value of the tranunloadpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANUNLOADPOINT() {
        return tranunloadpoint;
    }

    /**
     * Sets the value of the tranunloadpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANUNLOADPOINT(String value) {
        this.tranunloadpoint = value;
    }

    /**
     * Gets the value of the tranredirect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANREDIRECT() {
        return tranredirect;
    }

    /**
     * Sets the value of the tranredirect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANREDIRECT(String value) {
        this.tranredirect = value;
    }

    /**
     * Gets the value of the tranforwarder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANFORWARDER() {
        return tranforwarder;
    }

    /**
     * Sets the value of the tranforwarder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANFORWARDER(String value) {
        this.tranforwarder = value;
    }

}
