//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.requestadjustmentdata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WbType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WbType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WBInvoiceFromMe"/>
 *     &lt;enumeration value="WBReturnFromMe"/>
 *     &lt;enumeration value="WBInternal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WbType")
@XmlEnum
public enum WbType {

    @XmlEnumValue("WBInvoiceFromMe")
    WB_INVOICE_FROM_ME("WBInvoiceFromMe"),
    @XmlEnumValue("WBReturnFromMe")
    WB_RETURN_FROM_ME("WBReturnFromMe"),
    @XmlEnumValue("WBInternal")
    WB_INTERNAL("WBInternal");
    private final String value;

    WbType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WbType fromValue(String v) {
        for (WbType c: WbType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
