//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.actconfirmonlineorder;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.fsrar.wegais.commonv3.InformF2TypeItemBC;


/**
 * информация о форме2 (для все продукции) и кодах марок (для маркируемой продукции)
 * 
 * <p>Java class for F2DetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="F2DetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="InformF2" type="{http://fsrar.ru/WEGAIS/CommonV3}InformF2TypeItemBC"/>
 *         &lt;element name="QuantityF2" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *         &lt;element name="Price" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "F2DetailType", propOrder = {

})
public class F2DetailType {

    @XmlElement(name = "InformF2", required = true)
    protected InformF2TypeItemBC informF2;
    @XmlElement(name = "QuantityF2", required = true)
    protected BigDecimal quantityF2;
    @XmlElement(name = "Price", required = true)
    protected BigDecimal price;

    /**
     * Gets the value of the informF2 property.
     * 
     * @return
     *     possible object is
     *     {@link InformF2TypeItemBC }
     *     
     */
    public InformF2TypeItemBC getInformF2() {
        return informF2;
    }

    /**
     * Sets the value of the informF2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformF2TypeItemBC }
     *     
     */
    public void setInformF2(InformF2TypeItemBC value) {
        this.informF2 = value;
    }

    /**
     * Gets the value of the quantityF2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantityF2() {
        return quantityF2;
    }

    /**
     * Sets the value of the quantityF2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantityF2(BigDecimal value) {
        this.quantityF2 = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

}
