//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.actconfirmonlineorder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.actconfirmonlineorder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.actconfirmonlineorder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActConfirmOnlineOrderPositionType }
     * 
     */
    public ActConfirmOnlineOrderPositionType createActConfirmOnlineOrderPositionType() {
        return new ActConfirmOnlineOrderPositionType();
    }

    /**
     * Create an instance of {@link ActConfirmOnlineOrderType }
     * 
     */
    public ActConfirmOnlineOrderType createActConfirmOnlineOrderType() {
        return new ActConfirmOnlineOrderType();
    }

    /**
     * Create an instance of {@link F2DetailType }
     * 
     */
    public F2DetailType createF2DetailType() {
        return new F2DetailType();
    }

    /**
     * Create an instance of {@link ActConfirmOnlineOrderPositionType.F2Detail }
     * 
     */
    public ActConfirmOnlineOrderPositionType.F2Detail createActConfirmOnlineOrderPositionTypeF2Detail() {
        return new ActConfirmOnlineOrderPositionType.F2Detail();
    }

    /**
     * Create an instance of {@link ActConfirmOnlineOrderType.Header }
     * 
     */
    public ActConfirmOnlineOrderType.Header createActConfirmOnlineOrderTypeHeader() {
        return new ActConfirmOnlineOrderType.Header();
    }

    /**
     * Create an instance of {@link ActConfirmOnlineOrderType.Content }
     * 
     */
    public ActConfirmOnlineOrderType.Content createActConfirmOnlineOrderTypeContent() {
        return new ActConfirmOnlineOrderType.Content();
    }

}
