//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.carriernotice_v4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.fsrar.wegais.clientref_v2.OrgInfoRusV2;
import ru.fsrar.wegais.clientref_v2.OrgInfoV2;


/**
 * ”ведомление о перевозке
 * 
 * <p>Java class for CarrierNotice_v4 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarrierNotice_v4">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ClientIdentity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType" minOccurs="0"/>
 *                   &lt;element name="Serial" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *                   &lt;element name="Shipper" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfo_v2"/>
 *                   &lt;element name="Consignee" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfo_v2"/>
 *                   &lt;element name="Carrier" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_v2"/>
 *                   &lt;element name="ClientTransport" type="{http://fsrar.ru/WEGAIS/CarrierNotice_v4}ClientTransportType"/>
 *                   &lt;element name="ShipmentOutDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="ShipmentInDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="EGAISFixNumberTTN" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *                   &lt;element name="NotifNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="NotifDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/CarrierNotice_v4}PositionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarrierNotice_v4", propOrder = {
    "header",
    "content"
})
public class CarrierNoticeV4 {

    @XmlElement(name = "Header", required = true)
    protected CarrierNoticeV4 .Header header;
    @XmlElement(name = "Content", required = true)
    protected CarrierNoticeV4 .Content content;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierNoticeV4 .Header }
     *     
     */
    public CarrierNoticeV4 .Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierNoticeV4 .Header }
     *     
     */
    public void setHeader(CarrierNoticeV4 .Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierNoticeV4 .Content }
     *     
     */
    public CarrierNoticeV4 .Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierNoticeV4 .Content }
     *     
     */
    public void setContent(CarrierNoticeV4 .Content value) {
        this.content = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/CarrierNotice_v4}PositionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class Content {

        @XmlElement(name = "Position", required = true)
        protected List<PositionType> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PositionType }
         * 
         * 
         */
        public List<PositionType> getPosition() {
            if (position == null) {
                position = new ArrayList<PositionType>();
            }
            return this.position;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ClientIdentity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType" minOccurs="0"/>
     *         &lt;element name="Serial" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
     *         &lt;element name="Shipper" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfo_v2"/>
     *         &lt;element name="Consignee" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfo_v2"/>
     *         &lt;element name="Carrier" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_v2"/>
     *         &lt;element name="ClientTransport" type="{http://fsrar.ru/WEGAIS/CarrierNotice_v4}ClientTransportType"/>
     *         &lt;element name="ShipmentOutDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="ShipmentInDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="EGAISFixNumberTTN" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
     *         &lt;element name="NotifNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="NotifDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Header {

        @XmlElement(name = "ClientIdentity")
        protected String clientIdentity;
        @XmlElement(name = "Serial")
        protected String serial;
        @XmlElement(name = "Shipper", required = true)
        protected OrgInfoV2 shipper;
        @XmlElement(name = "Consignee", required = true)
        protected OrgInfoV2 consignee;
        @XmlElement(name = "Carrier", required = true)
        protected OrgInfoRusV2 carrier;
        @XmlElement(name = "ClientTransport", required = true)
        protected ClientTransportType clientTransport;
        @XmlElement(name = "ShipmentOutDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar shipmentOutDate;
        @XmlElement(name = "ShipmentInDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar shipmentInDate;
        @XmlElement(name = "EGAISFixNumberTTN")
        protected String egaisFixNumberTTN;
        @XmlElement(name = "NotifNumber", required = true)
        protected String notifNumber;
        @XmlElement(name = "NotifDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar notifDate;

        /**
         * Gets the value of the clientIdentity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientIdentity() {
            return clientIdentity;
        }

        /**
         * Sets the value of the clientIdentity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientIdentity(String value) {
            this.clientIdentity = value;
        }

        /**
         * Gets the value of the serial property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerial() {
            return serial;
        }

        /**
         * Sets the value of the serial property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerial(String value) {
            this.serial = value;
        }

        /**
         * Gets the value of the shipper property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoV2 }
         *     
         */
        public OrgInfoV2 getShipper() {
            return shipper;
        }

        /**
         * Sets the value of the shipper property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoV2 }
         *     
         */
        public void setShipper(OrgInfoV2 value) {
            this.shipper = value;
        }

        /**
         * Gets the value of the consignee property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoV2 }
         *     
         */
        public OrgInfoV2 getConsignee() {
            return consignee;
        }

        /**
         * Sets the value of the consignee property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoV2 }
         *     
         */
        public void setConsignee(OrgInfoV2 value) {
            this.consignee = value;
        }

        /**
         * Gets the value of the carrier property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoRusV2 }
         *     
         */
        public OrgInfoRusV2 getCarrier() {
            return carrier;
        }

        /**
         * Sets the value of the carrier property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoRusV2 }
         *     
         */
        public void setCarrier(OrgInfoRusV2 value) {
            this.carrier = value;
        }

        /**
         * Gets the value of the clientTransport property.
         * 
         * @return
         *     possible object is
         *     {@link ClientTransportType }
         *     
         */
        public ClientTransportType getClientTransport() {
            return clientTransport;
        }

        /**
         * Sets the value of the clientTransport property.
         * 
         * @param value
         *     allowed object is
         *     {@link ClientTransportType }
         *     
         */
        public void setClientTransport(ClientTransportType value) {
            this.clientTransport = value;
        }

        /**
         * Gets the value of the shipmentOutDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getShipmentOutDate() {
            return shipmentOutDate;
        }

        /**
         * Sets the value of the shipmentOutDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setShipmentOutDate(XMLGregorianCalendar value) {
            this.shipmentOutDate = value;
        }

        /**
         * Gets the value of the shipmentInDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getShipmentInDate() {
            return shipmentInDate;
        }

        /**
         * Sets the value of the shipmentInDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setShipmentInDate(XMLGregorianCalendar value) {
            this.shipmentInDate = value;
        }

        /**
         * Gets the value of the egaisFixNumberTTN property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEGAISFixNumberTTN() {
            return egaisFixNumberTTN;
        }

        /**
         * Sets the value of the egaisFixNumberTTN property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEGAISFixNumberTTN(String value) {
            this.egaisFixNumberTTN = value;
        }

        /**
         * Gets the value of the notifNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotifNumber() {
            return notifNumber;
        }

        /**
         * Sets the value of the notifNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotifNumber(String value) {
            this.notifNumber = value;
        }

        /**
         * Gets the value of the notifDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getNotifDate() {
            return notifDate;
        }

        /**
         * Sets the value of the notifDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setNotifDate(XMLGregorianCalendar value) {
            this.notifDate = value;
        }

    }

}
