//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.carriernotice_v4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ∆елезнодорожный транспорт
 * 
 * <p>Java class for RailwayType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RailwayType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="RailwayModel" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString2000"/>
 *         &lt;element name="RailwayVid" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString2000"/>
 *         &lt;element name="RailwayNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RailwayType", propOrder = {

})
public class RailwayType {

    @XmlElement(name = "RailwayModel", required = true)
    protected String railwayModel;
    @XmlElement(name = "RailwayVid", required = true)
    protected String railwayVid;
    @XmlElement(name = "RailwayNumber", required = true)
    protected String railwayNumber;

    /**
     * Gets the value of the railwayModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRailwayModel() {
        return railwayModel;
    }

    /**
     * Sets the value of the railwayModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRailwayModel(String value) {
        this.railwayModel = value;
    }

    /**
     * Gets the value of the railwayVid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRailwayVid() {
        return railwayVid;
    }

    /**
     * Sets the value of the railwayVid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRailwayVid(String value) {
        this.railwayVid = value;
    }

    /**
     * Gets the value of the railwayNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRailwayNumber() {
        return railwayNumber;
    }

    /**
     * Sets the value of the railwayNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRailwayNumber(String value) {
        this.railwayNumber = value;
    }

}
