//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.reportdestructionamfsm;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Позиция
 * 
 * <p>Java class for PositionAMFSMType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionAMFSMType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType"/>
 *         &lt;element name="CauseOfDestruction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SampleFSM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MarkType" type="{http://fsrar.ru/WEGAIS/Common}MarkGZTypeString"/>
 *         &lt;element name="RollNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="RangeNumberInRoll" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Rank" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}RankType"/>
 *         &lt;element name="Start" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}MarkNumberType"/>
 *         &lt;element name="Last" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}MarkNumberType"/>
 *         &lt;element name="QuantityRange" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionAMFSMType", propOrder = {

})
public class PositionAMFSMType {

    @XmlElement(name = "Identity", required = true)
    protected String identity;
    @XmlElement(name = "CauseOfDestruction", required = true)
    protected String causeOfDestruction;
    @XmlElement(name = "SampleFSM", required = true)
    protected String sampleFSM;
    @XmlElement(name = "MarkType", required = true)
    protected String markType;
    @XmlElement(name = "RollNumber")
    protected BigInteger rollNumber;
    @XmlElement(name = "RangeNumberInRoll")
    protected BigInteger rangeNumberInRoll;
    @XmlElement(name = "Rank", required = true)
    protected String rank;
    @XmlElement(name = "Start", required = true)
    protected String start;
    @XmlElement(name = "Last", required = true)
    protected String last;
    @XmlElement(name = "QuantityRange", required = true)
    protected BigInteger quantityRange;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the causeOfDestruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCauseOfDestruction() {
        return causeOfDestruction;
    }

    /**
     * Sets the value of the causeOfDestruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCauseOfDestruction(String value) {
        this.causeOfDestruction = value;
    }

    /**
     * Gets the value of the sampleFSM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleFSM() {
        return sampleFSM;
    }

    /**
     * Sets the value of the sampleFSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleFSM(String value) {
        this.sampleFSM = value;
    }

    /**
     * Gets the value of the markType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkType() {
        return markType;
    }

    /**
     * Sets the value of the markType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkType(String value) {
        this.markType = value;
    }

    /**
     * Gets the value of the rollNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRollNumber() {
        return rollNumber;
    }

    /**
     * Sets the value of the rollNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRollNumber(BigInteger value) {
        this.rollNumber = value;
    }

    /**
     * Gets the value of the rangeNumberInRoll property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRangeNumberInRoll() {
        return rangeNumberInRoll;
    }

    /**
     * Sets the value of the rangeNumberInRoll property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRangeNumberInRoll(BigInteger value) {
        this.rangeNumberInRoll = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStart(String value) {
        this.start = value;
    }

    /**
     * Gets the value of the last property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLast() {
        return last;
    }

    /**
     * Sets the value of the last property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLast(String value) {
        this.last = value;
    }

    /**
     * Gets the value of the quantityRange property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantityRange() {
        return quantityRange;
    }

    /**
     * Sets the value of the quantityRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantityRange(BigInteger value) {
        this.quantityRange = value;
    }

}
