//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fsrar.ru/WEGAIS/ReplyAP_v3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.fsrar.wegais.replyap_v3;
