//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.requestmanufacturerfsm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.requestmanufacturerfsm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.requestmanufacturerfsm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestManufacturerFSMType }
     * 
     */
    public RequestManufacturerFSMType createRequestManufacturerFSMType() {
        return new RequestManufacturerFSMType();
    }

    /**
     * Create an instance of {@link PositionReportType }
     * 
     */
    public PositionReportType createPositionReportType() {
        return new PositionReportType();
    }

    /**
     * Create an instance of {@link RequestManufacturerFSMType.Header }
     * 
     */
    public RequestManufacturerFSMType.Header createRequestManufacturerFSMTypeHeader() {
        return new RequestManufacturerFSMType.Header();
    }

    /**
     * Create an instance of {@link RequestManufacturerFSMType.Content }
     * 
     */
    public RequestManufacturerFSMType.Content createRequestManufacturerFSMTypeContent() {
        return new RequestManufacturerFSMType.Content();
    }

}
