//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * расчёт потребностей в ФСМ
 * 
 * <p>Java class for CalculationDemandType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculationDemandType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Spirit" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}SpiritType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WineMaterial" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}WineMaterialType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RawAged" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}RawAgedType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MarkedAP" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}MarkedAPType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WinemakingAP" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}WinemakingAPType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WinemakingAPSTP" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}WinemakingAPSTPType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculationDemandType", propOrder = {
    "spirit",
    "wineMaterial",
    "rawAged",
    "markedAP",
    "winemakingAP",
    "winemakingAPSTP"
})
public class CalculationDemandType {

    @XmlElement(name = "Spirit")
    protected List<SpiritType> spirit;
    @XmlElement(name = "WineMaterial")
    protected List<WineMaterialType> wineMaterial;
    @XmlElement(name = "RawAged")
    protected List<RawAgedType> rawAged;
    @XmlElement(name = "MarkedAP")
    protected List<MarkedAPType> markedAP;
    @XmlElement(name = "WinemakingAP")
    protected List<WinemakingAPType> winemakingAP;
    @XmlElement(name = "WinemakingAPSTP")
    protected List<WinemakingAPSTPType> winemakingAPSTP;

    /**
     * Gets the value of the spirit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spirit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpirit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpiritType }
     * 
     * 
     */
    public List<SpiritType> getSpirit() {
        if (spirit == null) {
            spirit = new ArrayList<SpiritType>();
        }
        return this.spirit;
    }

    /**
     * Gets the value of the wineMaterial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wineMaterial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWineMaterial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WineMaterialType }
     * 
     * 
     */
    public List<WineMaterialType> getWineMaterial() {
        if (wineMaterial == null) {
            wineMaterial = new ArrayList<WineMaterialType>();
        }
        return this.wineMaterial;
    }

    /**
     * Gets the value of the rawAged property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rawAged property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRawAged().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RawAgedType }
     * 
     * 
     */
    public List<RawAgedType> getRawAged() {
        if (rawAged == null) {
            rawAged = new ArrayList<RawAgedType>();
        }
        return this.rawAged;
    }

    /**
     * Gets the value of the markedAP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the markedAP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarkedAP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarkedAPType }
     * 
     * 
     */
    public List<MarkedAPType> getMarkedAP() {
        if (markedAP == null) {
            markedAP = new ArrayList<MarkedAPType>();
        }
        return this.markedAP;
    }

    /**
     * Gets the value of the winemakingAP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the winemakingAP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWinemakingAP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WinemakingAPType }
     * 
     * 
     */
    public List<WinemakingAPType> getWinemakingAP() {
        if (winemakingAP == null) {
            winemakingAP = new ArrayList<WinemakingAPType>();
        }
        return this.winemakingAP;
    }

    /**
     * Gets the value of the winemakingAPSTP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the winemakingAPSTP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWinemakingAPSTP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WinemakingAPSTPType }
     * 
     * 
     */
    public List<WinemakingAPSTPType> getWinemakingAPSTP() {
        if (winemakingAPSTP == null) {
            winemakingAPSTP = new ArrayList<WinemakingAPSTPType>();
        }
        return this.winemakingAPSTP;
    }

}
