//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Типы заявок на получение ФСМ
 * 
 * <p>Java class for ClaimIssueFSMComplType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimIssueFSMComplType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TypeClaim1" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}producedru"/>
 *         &lt;element name="TypeClaim3" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}producedts"/>
 *         &lt;element name="TypeClaim2" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}producedimp"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimIssueFSMComplType", propOrder = {
    "typeClaim1",
    "typeClaim3",
    "typeClaim2"
})
public class ClaimIssueFSMComplType {

    @XmlElement(name = "TypeClaim1")
    protected Producedru typeClaim1;
    @XmlElement(name = "TypeClaim3")
    protected Producedts typeClaim3;
    @XmlElement(name = "TypeClaim2")
    protected Producedimp typeClaim2;

    /**
     * Gets the value of the typeClaim1 property.
     * 
     * @return
     *     possible object is
     *     {@link Producedru }
     *     
     */
    public Producedru getTypeClaim1() {
        return typeClaim1;
    }

    /**
     * Sets the value of the typeClaim1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Producedru }
     *     
     */
    public void setTypeClaim1(Producedru value) {
        this.typeClaim1 = value;
    }

    /**
     * Gets the value of the typeClaim3 property.
     * 
     * @return
     *     possible object is
     *     {@link Producedts }
     *     
     */
    public Producedts getTypeClaim3() {
        return typeClaim3;
    }

    /**
     * Sets the value of the typeClaim3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Producedts }
     *     
     */
    public void setTypeClaim3(Producedts value) {
        this.typeClaim3 = value;
    }

    /**
     * Gets the value of the typeClaim2 property.
     * 
     * @return
     *     possible object is
     *     {@link Producedimp }
     *     
     */
    public Producedimp getTypeClaim2() {
        return typeClaim2;
    }

    /**
     * Sets the value of the typeClaim2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Producedimp }
     *     
     */
    public void setTypeClaim2(Producedimp value) {
        this.typeClaim2 = value;
    }

}
