//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.fsrar.wegais.clientref_v2.OrgInfoRusClaimIssue;
import ru.fsrar.wegais.commonenum.ReportUseAutoProcessType;


/**
 * Заявление о выдаче ФСМ
 * 
 * <p>Java class for ClaimIssueFSMType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimIssueFSMType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType" minOccurs="0"/>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="NUMBER" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="Date" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="TerrOrganRAR" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue" minOccurs="0"/>
 *                   &lt;element name="Declarer" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue"/>
 *                   &lt;element name="Note" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="200"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ReportUseAutoProcess" type="{http://fsrar.ru/WEGAIS/CommonEnum}ReportUseAutoProcessType" minOccurs="0"/>
 *                   &lt;element name="ParentClaimID" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *                   &lt;element name="TypeClaimM" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}ClaimIssueFSMComplType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}PositionClaimType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CalculationDemand" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}CalculationDemandType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimIssueFSMType", propOrder = {
    "identity",
    "header",
    "content",
    "calculationDemand"
})
public class ClaimIssueFSMType {

    @XmlElement(name = "Identity")
    protected String identity;
    @XmlElement(name = "Header", required = true)
    protected ClaimIssueFSMType.Header header;
    @XmlElement(name = "Content", required = true)
    protected ClaimIssueFSMType.Content content;
    @XmlElement(name = "CalculationDemand")
    protected CalculationDemandType calculationDemand;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimIssueFSMType.Header }
     *     
     */
    public ClaimIssueFSMType.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimIssueFSMType.Header }
     *     
     */
    public void setHeader(ClaimIssueFSMType.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimIssueFSMType.Content }
     *     
     */
    public ClaimIssueFSMType.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimIssueFSMType.Content }
     *     
     */
    public void setContent(ClaimIssueFSMType.Content value) {
        this.content = value;
    }

    /**
     * Gets the value of the calculationDemand property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationDemandType }
     *     
     */
    public CalculationDemandType getCalculationDemand() {
        return calculationDemand;
    }

    /**
     * Sets the value of the calculationDemand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationDemandType }
     *     
     */
    public void setCalculationDemand(CalculationDemandType value) {
        this.calculationDemand = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}PositionClaimType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class Content {

        @XmlElement(name = "Position", required = true)
        protected List<PositionClaimType> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PositionClaimType }
         * 
         * 
         */
        public List<PositionClaimType> getPosition() {
            if (position == null) {
                position = new ArrayList<PositionClaimType>();
            }
            return this.position;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="NUMBER" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="Date" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="TerrOrganRAR" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue" minOccurs="0"/>
     *         &lt;element name="Declarer" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue"/>
     *         &lt;element name="Note" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="200"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ReportUseAutoProcess" type="{http://fsrar.ru/WEGAIS/CommonEnum}ReportUseAutoProcessType" minOccurs="0"/>
     *         &lt;element name="ParentClaimID" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
     *         &lt;element name="TypeClaimM" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}ClaimIssueFSMComplType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Header {

        @XmlElement(name = "NUMBER", required = true)
        protected String number;
        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "TerrOrganRAR")
        protected OrgInfoRusClaimIssue terrOrganRAR;
        @XmlElement(name = "Declarer", required = true)
        protected OrgInfoRusClaimIssue declarer;
        @XmlElement(name = "Note")
        protected String note;
        @XmlElement(name = "ReportUseAutoProcess")
        @XmlSchemaType(name = "string")
        protected ReportUseAutoProcessType reportUseAutoProcess;
        @XmlElement(name = "ParentClaimID")
        protected String parentClaimID;
        @XmlElement(name = "TypeClaimM", required = true)
        protected ClaimIssueFSMComplType typeClaimM;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNUMBER() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNUMBER(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the terrOrganRAR property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public OrgInfoRusClaimIssue getTerrOrganRAR() {
            return terrOrganRAR;
        }

        /**
         * Sets the value of the terrOrganRAR property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public void setTerrOrganRAR(OrgInfoRusClaimIssue value) {
            this.terrOrganRAR = value;
        }

        /**
         * Gets the value of the declarer property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public OrgInfoRusClaimIssue getDeclarer() {
            return declarer;
        }

        /**
         * Sets the value of the declarer property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public void setDeclarer(OrgInfoRusClaimIssue value) {
            this.declarer = value;
        }

        /**
         * Gets the value of the note property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNote() {
            return note;
        }

        /**
         * Sets the value of the note property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNote(String value) {
            this.note = value;
        }

        /**
         * Gets the value of the reportUseAutoProcess property.
         * 
         * @return
         *     possible object is
         *     {@link ReportUseAutoProcessType }
         *     
         */
        public ReportUseAutoProcessType getReportUseAutoProcess() {
            return reportUseAutoProcess;
        }

        /**
         * Sets the value of the reportUseAutoProcess property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReportUseAutoProcessType }
         *     
         */
        public void setReportUseAutoProcess(ReportUseAutoProcessType value) {
            this.reportUseAutoProcess = value;
        }

        /**
         * Gets the value of the parentClaimID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentClaimID() {
            return parentClaimID;
        }

        /**
         * Sets the value of the parentClaimID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentClaimID(String value) {
            this.parentClaimID = value;
        }

        /**
         * Gets the value of the typeClaimM property.
         * 
         * @return
         *     possible object is
         *     {@link ClaimIssueFSMComplType }
         *     
         */
        public ClaimIssueFSMComplType getTypeClaimM() {
            return typeClaimM;
        }

        /**
         * Sets the value of the typeClaimM property.
         * 
         * @param value
         *     allowed object is
         *     {@link ClaimIssueFSMComplType }
         *     
         */
        public void setTypeClaimM(ClaimIssueFSMComplType value) {
            this.typeClaimM = value;
        }

    }

}
