//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Объём маркируемой АП
 * 
 * <p>Java class for MarkedAPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarkedAPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="RestFSM" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeMarkedProductType"/>
 *         &lt;element name="RequestFSM" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeMarkedProductType"/>
 *         &lt;element name="TotalVolumeAnhydrousSpirit" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *         &lt;element name="TotalVolumeMarkedAP" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkedAPType", propOrder = {

})
public class MarkedAPType {

    @XmlElement(name = "RestFSM", required = true)
    protected VolumeMarkedProductType restFSM;
    @XmlElement(name = "RequestFSM", required = true)
    protected VolumeMarkedProductType requestFSM;
    @XmlElement(name = "TotalVolumeAnhydrousSpirit", required = true)
    protected BigDecimal totalVolumeAnhydrousSpirit;
    @XmlElement(name = "TotalVolumeMarkedAP", required = true)
    protected BigDecimal totalVolumeMarkedAP;

    /**
     * Gets the value of the restFSM property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMarkedProductType }
     *     
     */
    public VolumeMarkedProductType getRestFSM() {
        return restFSM;
    }

    /**
     * Sets the value of the restFSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMarkedProductType }
     *     
     */
    public void setRestFSM(VolumeMarkedProductType value) {
        this.restFSM = value;
    }

    /**
     * Gets the value of the requestFSM property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMarkedProductType }
     *     
     */
    public VolumeMarkedProductType getRequestFSM() {
        return requestFSM;
    }

    /**
     * Sets the value of the requestFSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMarkedProductType }
     *     
     */
    public void setRequestFSM(VolumeMarkedProductType value) {
        this.requestFSM = value;
    }

    /**
     * Gets the value of the totalVolumeAnhydrousSpirit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalVolumeAnhydrousSpirit() {
        return totalVolumeAnhydrousSpirit;
    }

    /**
     * Sets the value of the totalVolumeAnhydrousSpirit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalVolumeAnhydrousSpirit(BigDecimal value) {
        this.totalVolumeAnhydrousSpirit = value;
    }

    /**
     * Gets the value of the totalVolumeMarkedAP property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalVolumeMarkedAP() {
        return totalVolumeMarkedAP;
    }

    /**
     * Sets the value of the totalVolumeMarkedAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalVolumeMarkedAP(BigDecimal value) {
        this.totalVolumeMarkedAP = value;
    }

}
