//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.claimissuefsm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.claimissuefsm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClaimIssueFSMType }
     * 
     */
    public ClaimIssueFSMType createClaimIssueFSMType() {
        return new ClaimIssueFSMType();
    }

    /**
     * Create an instance of {@link VolumeLocateAgainRawType }
     * 
     */
    public VolumeLocateAgainRawType createVolumeLocateAgainRawType() {
        return new VolumeLocateAgainRawType();
    }

    /**
     * Create an instance of {@link Producedimp }
     * 
     */
    public Producedimp createProducedimp() {
        return new Producedimp();
    }

    /**
     * Create an instance of {@link WinemakingAPType }
     * 
     */
    public WinemakingAPType createWinemakingAPType() {
        return new WinemakingAPType();
    }

    /**
     * Create an instance of {@link PositionClaimType }
     * 
     */
    public PositionClaimType createPositionClaimType() {
        return new PositionClaimType();
    }

    /**
     * Create an instance of {@link WineMaterialType }
     * 
     */
    public WineMaterialType createWineMaterialType() {
        return new WineMaterialType();
    }

    /**
     * Create an instance of {@link VolumeSpiritType }
     * 
     */
    public VolumeSpiritType createVolumeSpiritType() {
        return new VolumeSpiritType();
    }

    /**
     * Create an instance of {@link MarkedAPType }
     * 
     */
    public MarkedAPType createMarkedAPType() {
        return new MarkedAPType();
    }

    /**
     * Create an instance of {@link Producedru }
     * 
     */
    public Producedru createProducedru() {
        return new Producedru();
    }

    /**
     * Create an instance of {@link VolumeUsedRawType }
     * 
     */
    public VolumeUsedRawType createVolumeUsedRawType() {
        return new VolumeUsedRawType();
    }

    /**
     * Create an instance of {@link SpiritType }
     * 
     */
    public SpiritType createSpiritType() {
        return new SpiritType();
    }

    /**
     * Create an instance of {@link RawAgedType }
     * 
     */
    public RawAgedType createRawAgedType() {
        return new RawAgedType();
    }

    /**
     * Create an instance of {@link CalculationDemandType }
     * 
     */
    public CalculationDemandType createCalculationDemandType() {
        return new CalculationDemandType();
    }

    /**
     * Create an instance of {@link Producedts }
     * 
     */
    public Producedts createProducedts() {
        return new Producedts();
    }

    /**
     * Create an instance of {@link VolumeMarkedProductType }
     * 
     */
    public VolumeMarkedProductType createVolumeMarkedProductType() {
        return new VolumeMarkedProductType();
    }

    /**
     * Create an instance of {@link VolumeReceivedRawType }
     * 
     */
    public VolumeReceivedRawType createVolumeReceivedRawType() {
        return new VolumeReceivedRawType();
    }

    /**
     * Create an instance of {@link WinemakingAPSTPType }
     * 
     */
    public WinemakingAPSTPType createWinemakingAPSTPType() {
        return new WinemakingAPSTPType();
    }

    /**
     * Create an instance of {@link ClaimIssueFSMComplType }
     * 
     */
    public ClaimIssueFSMComplType createClaimIssueFSMComplType() {
        return new ClaimIssueFSMComplType();
    }

    /**
     * Create an instance of {@link ClaimRawType }
     * 
     */
    public ClaimRawType createClaimRawType() {
        return new ClaimRawType();
    }

    /**
     * Create an instance of {@link ClaimIssueFSMType.Header }
     * 
     */
    public ClaimIssueFSMType.Header createClaimIssueFSMTypeHeader() {
        return new ClaimIssueFSMType.Header();
    }

    /**
     * Create an instance of {@link ClaimIssueFSMType.Content }
     * 
     */
    public ClaimIssueFSMType.Content createClaimIssueFSMTypeContent() {
        return new ClaimIssueFSMType.Content();
    }

}
