//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Позиция
 * 
 * <p>Java class for PositionClaimType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionClaimType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="VidAP171fz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alcPercent" type="{http://fsrar.ru/WEGAIS/Common}AlcPercentType"/>
 *         &lt;element name="QuantityDal" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *         &lt;element name="Capacity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType"/>
 *         &lt;element name="SampleFSM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MarkType" type="{http://fsrar.ru/WEGAIS/Common}MarkGZTypeString"/>
 *         &lt;element name="Quantity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionClaimType", propOrder = {

})
public class PositionClaimType {

    @XmlElement(name = "VidAP171fz", required = true)
    protected String vidAP171Fz;
    @XmlElement(required = true)
    protected BigDecimal alcPercent;
    @XmlElement(name = "QuantityDal", required = true)
    protected BigDecimal quantityDal;
    @XmlElement(name = "Capacity", required = true)
    protected BigDecimal capacity;
    @XmlElement(name = "Identity", required = true)
    protected String identity;
    @XmlElement(name = "SampleFSM", required = true)
    protected String sampleFSM;
    @XmlElement(name = "MarkType", required = true)
    protected String markType;
    @XmlElement(name = "Quantity", required = true)
    protected BigDecimal quantity;

    /**
     * Gets the value of the vidAP171Fz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVidAP171Fz() {
        return vidAP171Fz;
    }

    /**
     * Sets the value of the vidAP171Fz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVidAP171Fz(String value) {
        this.vidAP171Fz = value;
    }

    /**
     * Gets the value of the alcPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlcPercent() {
        return alcPercent;
    }

    /**
     * Sets the value of the alcPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlcPercent(BigDecimal value) {
        this.alcPercent = value;
    }

    /**
     * Gets the value of the quantityDal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantityDal() {
        return quantityDal;
    }

    /**
     * Sets the value of the quantityDal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantityDal(BigDecimal value) {
        this.quantityDal = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacity(BigDecimal value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the sampleFSM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleFSM() {
        return sampleFSM;
    }

    /**
     * Sets the value of the sampleFSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleFSM(String value) {
        this.sampleFSM = value;
    }

    /**
     * Gets the value of the markType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkType() {
        return markType;
    }

    /**
     * Sets the value of the markType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkType(String value) {
        this.markType = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

}
