//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ќбъЄм использованного сырь¤ с даты предыдущего отчЄта
 * 
 * <p>Java class for VolumeUsedRawType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolumeUsedRawType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="VolumeToAgingRaw" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeSpiritType"/>
 *         &lt;element name="VolumeToProducedRaw" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeSpiritType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolumeUsedRawType", propOrder = {

})
public class VolumeUsedRawType {

    @XmlElement(name = "VolumeToAgingRaw", required = true)
    protected VolumeSpiritType volumeToAgingRaw;
    @XmlElement(name = "VolumeToProducedRaw", required = true)
    protected VolumeSpiritType volumeToProducedRaw;

    /**
     * Gets the value of the volumeToAgingRaw property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeSpiritType }
     *     
     */
    public VolumeSpiritType getVolumeToAgingRaw() {
        return volumeToAgingRaw;
    }

    /**
     * Sets the value of the volumeToAgingRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeSpiritType }
     *     
     */
    public void setVolumeToAgingRaw(VolumeSpiritType value) {
        this.volumeToAgingRaw = value;
    }

    /**
     * Gets the value of the volumeToProducedRaw property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeSpiritType }
     *     
     */
    public VolumeSpiritType getVolumeToProducedRaw() {
        return volumeToProducedRaw;
    }

    /**
     * Sets the value of the volumeToProducedRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeSpiritType }
     *     
     */
    public void setVolumeToProducedRaw(VolumeSpiritType value) {
        this.volumeToProducedRaw = value;
    }

}
