//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Объём маркируемой АП
 * 
 * <p>Java class for VolumeMarkedProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolumeMarkedProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="SampleFSM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VidAP171fz" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VolumeSpirit" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *         &lt;element name="VolumeMarkedAP" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *         &lt;element name="Capacity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *         &lt;element name="AmountFSM" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *         &lt;element name="VolumeAnhydrousSpirit" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeDecimalType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolumeMarkedProductType", propOrder = {

})
public class VolumeMarkedProductType {

    @XmlElement(name = "SampleFSM")
    protected String sampleFSM;
    @XmlElement(name = "VidAP171fz", required = true)
    protected String vidAP171Fz;
    @XmlElement(name = "VolumeSpirit", required = true)
    protected BigDecimal volumeSpirit;
    @XmlElement(name = "VolumeMarkedAP", required = true)
    protected BigDecimal volumeMarkedAP;
    @XmlElement(name = "Capacity", required = true)
    protected BigDecimal capacity;
    @XmlElement(name = "AmountFSM", required = true)
    protected BigDecimal amountFSM;
    @XmlElement(name = "VolumeAnhydrousSpirit", required = true)
    protected BigDecimal volumeAnhydrousSpirit;

    /**
     * Gets the value of the sampleFSM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleFSM() {
        return sampleFSM;
    }

    /**
     * Sets the value of the sampleFSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleFSM(String value) {
        this.sampleFSM = value;
    }

    /**
     * Gets the value of the vidAP171Fz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVidAP171Fz() {
        return vidAP171Fz;
    }

    /**
     * Sets the value of the vidAP171Fz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVidAP171Fz(String value) {
        this.vidAP171Fz = value;
    }

    /**
     * Gets the value of the volumeSpirit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolumeSpirit() {
        return volumeSpirit;
    }

    /**
     * Sets the value of the volumeSpirit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVolumeSpirit(BigDecimal value) {
        this.volumeSpirit = value;
    }

    /**
     * Gets the value of the volumeMarkedAP property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolumeMarkedAP() {
        return volumeMarkedAP;
    }

    /**
     * Sets the value of the volumeMarkedAP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVolumeMarkedAP(BigDecimal value) {
        this.volumeMarkedAP = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacity(BigDecimal value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the amountFSM property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountFSM() {
        return amountFSM;
    }

    /**
     * Sets the value of the amountFSM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountFSM(BigDecimal value) {
        this.amountFSM = value;
    }

    /**
     * Gets the value of the volumeAnhydrousSpirit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVolumeAnhydrousSpirit() {
        return volumeAnhydrousSpirit;
    }

    /**
     * Sets the value of the volumeAnhydrousSpirit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVolumeAnhydrousSpirit(BigDecimal value) {
        this.volumeAnhydrousSpirit = value;
    }

}
