//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.claimissuefsm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ќбъЄм полученного сырь¤ с с даты предыдущего отчЄта
 * 
 * <p>Java class for VolumeReceivedRawType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolumeReceivedRawType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="VolumeFromAgingRaw" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeSpiritType"/>
 *         &lt;element name="VolumeBuyRaw" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeSpiritType"/>
 *         &lt;element name="VolumeConversionRaw" type="{http://fsrar.ru/WEGAIS/ClaimIssueFSM}VolumeSpiritType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolumeReceivedRawType", propOrder = {

})
public class VolumeReceivedRawType {

    @XmlElement(name = "VolumeFromAgingRaw", required = true)
    protected VolumeSpiritType volumeFromAgingRaw;
    @XmlElement(name = "VolumeBuyRaw", required = true)
    protected VolumeSpiritType volumeBuyRaw;
    @XmlElement(name = "VolumeConversionRaw", required = true)
    protected VolumeSpiritType volumeConversionRaw;

    /**
     * Gets the value of the volumeFromAgingRaw property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeSpiritType }
     *     
     */
    public VolumeSpiritType getVolumeFromAgingRaw() {
        return volumeFromAgingRaw;
    }

    /**
     * Sets the value of the volumeFromAgingRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeSpiritType }
     *     
     */
    public void setVolumeFromAgingRaw(VolumeSpiritType value) {
        this.volumeFromAgingRaw = value;
    }

    /**
     * Gets the value of the volumeBuyRaw property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeSpiritType }
     *     
     */
    public VolumeSpiritType getVolumeBuyRaw() {
        return volumeBuyRaw;
    }

    /**
     * Sets the value of the volumeBuyRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeSpiritType }
     *     
     */
    public void setVolumeBuyRaw(VolumeSpiritType value) {
        this.volumeBuyRaw = value;
    }

    /**
     * Gets the value of the volumeConversionRaw property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeSpiritType }
     *     
     */
    public VolumeSpiritType getVolumeConversionRaw() {
        return volumeConversionRaw;
    }

    /**
     * Sets the value of the volumeConversionRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeSpiritType }
     *     
     */
    public void setVolumeConversionRaw(VolumeSpiritType value) {
        this.volumeConversionRaw = value;
    }

}
