//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.productref_v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeclarationVidType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeclarationVidType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Декларация"/>
 *     &lt;enumeration value="Сертификат"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeclarationVidType")
@XmlEnum
public enum DeclarationVidType {

    @XmlEnumValue("\u0414\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0438\u044f")
    ДЕКЛАРАЦИЯ("\u0414\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0438\u044f"),
    @XmlEnumValue("\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442")
    СЕРТИФИКАТ("\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442");
    private final String value;

    DeclarationVidType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeclarationVidType fromValue(String v) {
        for (DeclarationVidType c: DeclarationVidType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
