//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.productref_v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DocumentVidType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DocumentVidType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ГОСТ"/>
 *     &lt;enumeration value="ТИ"/>
 *     &lt;enumeration value="ТУ"/>
 *     &lt;enumeration value="РЦ"/>
 *     &lt;enumeration value="Другое"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DocumentVidType")
@XmlEnum
public enum DocumentVidType {

    ГОСТ("\u0413\u041e\u0421\u0422"),
    ТИ("\u0422\u0418"),
    ТУ("\u0422\u0423"),
    РЦ("\u0420\u0426"),
    @XmlEnumValue("\u0414\u0440\u0443\u0433\u043e\u0435")
    ДРУГОЕ("\u0414\u0440\u0443\u0433\u043e\u0435");
    private final String value;

    DocumentVidType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DocumentVidType fromValue(String v) {
        for (DocumentVidType c: DocumentVidType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
