//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.productref_v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WbIngredientType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WbIngredientType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="основной"/>
 *     &lt;enumeration value="дополнительный"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WbIngredientType")
@XmlEnum
public enum WbIngredientType {

    @XmlEnumValue("\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439")
    ОСНОВНОЙ("\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439"),
    @XmlEnumValue("\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439")
    ДОПОЛНИТЕЛЬНЫЙ("\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439");
    private final String value;

    WbIngredientType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WbIngredientType fromValue(String v) {
        for (WbIngredientType c: WbIngredientType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
