//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.actttnsingle_v4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Транспортный раздел
 * 
 * <p>Java class for TransportActType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportActType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ChangeOwnership" type="{http://fsrar.ru/WEGAIS/ActTTNSingle_v4}WbChangeOwnershipType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportActType", propOrder = {

})
public class TransportActType {

    @XmlElement(name = "ChangeOwnership", required = true)
    @XmlSchemaType(name = "string")
    protected WbChangeOwnershipType changeOwnership;

    /**
     * Gets the value of the changeOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link WbChangeOwnershipType }
     *     
     */
    public WbChangeOwnershipType getChangeOwnership() {
        return changeOwnership;
    }

    /**
     * Sets the value of the changeOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link WbChangeOwnershipType }
     *     
     */
    public void setChangeOwnership(WbChangeOwnershipType value) {
        this.changeOwnership = value;
    }

}
