//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.chequev3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Чек, чек возврата, розница по безналу
 * 
 * <p>Java class for ChequeV3Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChequeV3Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="Header" type="{http://fsrar.ru/WEGAIS/ChequeV3}Header"/>
 *           &lt;element name="HeaderTTN" type="{http://fsrar.ru/WEGAIS/ChequeV3}HeaderTTN"/>
 *         &lt;/choice>
 *         &lt;element name="Content">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="Bottle" type="{http://fsrar.ru/WEGAIS/ChequeV3}Bottle"/>
 *                     &lt;element name="Nomark" type="{http://fsrar.ru/WEGAIS/ChequeV3}Nomark"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChequeV3Type", propOrder = {
    "identity",
    "header",
    "headerTTN",
    "content"
})
public class ChequeV3Type {

    @XmlElement(name = "Identity")
    protected String identity;
    @XmlElement(name = "Header")
    protected Header header;
    @XmlElement(name = "HeaderTTN")
    protected HeaderTTN headerTTN;
    @XmlElement(name = "Content", required = true)
    protected ChequeV3Type.Content content;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the headerTTN property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderTTN }
     *     
     */
    public HeaderTTN getHeaderTTN() {
        return headerTTN;
    }

    /**
     * Sets the value of the headerTTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderTTN }
     *     
     */
    public void setHeaderTTN(HeaderTTN value) {
        this.headerTTN = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ChequeV3Type.Content }
     *     
     */
    public ChequeV3Type.Content getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChequeV3Type.Content }
     *     
     */
    public void setContent(ChequeV3Type.Content value) {
        this.content = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded">
     *           &lt;element name="Bottle" type="{http://fsrar.ru/WEGAIS/ChequeV3}Bottle"/>
     *           &lt;element name="Nomark" type="{http://fsrar.ru/WEGAIS/ChequeV3}Nomark"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bottleOrNomark"
    })
    public static class Content {

        @XmlElements({
            @XmlElement(name = "Bottle", type = Bottle.class),
            @XmlElement(name = "Nomark", type = Nomark.class)
        })
        protected List<Object> bottleOrNomark;

        /**
         * Gets the value of the bottleOrNomark property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bottleOrNomark property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBottleOrNomark().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Bottle }
         * {@link Nomark }
         * 
         * 
         */
        public List<Object> getBottleOrNomark() {
            if (bottleOrNomark == null) {
                bottleOrNomark = new ArrayList<Object>();
            }
            return this.bottleOrNomark;
        }

    }

}
