//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.referenceofdeficiencies;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.fsrar.wegais.clientref_v2.OrgInfoRusClaimIssue;


/**
 * 
 *         СПРАВКА о наличии недостатков в представленных заявителем документах для выдачи федеральных специальных марок для маркировки алкогольной продукции, производимой на территории Российской Федерации
 *       
 * 
 * <p>Java class for ReferenceOfDeficiencies complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceOfDeficiencies">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ReferenceDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="RequestFSM" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="NUMBERIssueFSM" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="DateIssueFSM" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="TerrOrganRAR" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue" minOccurs="0"/>
 *                   &lt;element name="Declarer" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue"/>
 *                   &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SignReference" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                   &lt;element name="SignCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceOfDeficiencies", propOrder = {
    "header"
})
public class ReferenceOfDeficiencies {

    @XmlElement(name = "Header", required = true)
    protected ReferenceOfDeficiencies.Header header;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceOfDeficiencies.Header }
     *     
     */
    public ReferenceOfDeficiencies.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceOfDeficiencies.Header }
     *     
     */
    public void setHeader(ReferenceOfDeficiencies.Header value) {
        this.header = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ReferenceDate" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="RequestFSM" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="NUMBERIssueFSM" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="DateIssueFSM" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="TerrOrganRAR" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue" minOccurs="0"/>
     *         &lt;element name="Declarer" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoRus_ClaimIssue"/>
     *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SignReference" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *         &lt;element name="SignCertificate" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Header {

        @XmlElement(name = "ReferenceDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar referenceDate;
        @XmlElement(name = "RequestFSM", required = true)
        protected String requestFSM;
        @XmlElement(name = "NUMBERIssueFSM", required = true)
        protected String numberIssueFSM;
        @XmlElement(name = "DateIssueFSM", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateIssueFSM;
        @XmlElement(name = "TerrOrganRAR")
        protected OrgInfoRusClaimIssue terrOrganRAR;
        @XmlElement(name = "Declarer", required = true)
        protected OrgInfoRusClaimIssue declarer;
        @XmlElement(name = "Comments", required = true)
        protected String comments;
        @XmlElement(name = "SignReference")
        protected byte[] signReference;
        @XmlElement(name = "SignCertificate")
        protected byte[] signCertificate;

        /**
         * Gets the value of the referenceDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReferenceDate() {
            return referenceDate;
        }

        /**
         * Sets the value of the referenceDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReferenceDate(XMLGregorianCalendar value) {
            this.referenceDate = value;
        }

        /**
         * Gets the value of the requestFSM property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestFSM() {
            return requestFSM;
        }

        /**
         * Sets the value of the requestFSM property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestFSM(String value) {
            this.requestFSM = value;
        }

        /**
         * Gets the value of the numberIssueFSM property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNUMBERIssueFSM() {
            return numberIssueFSM;
        }

        /**
         * Sets the value of the numberIssueFSM property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNUMBERIssueFSM(String value) {
            this.numberIssueFSM = value;
        }

        /**
         * Gets the value of the dateIssueFSM property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateIssueFSM() {
            return dateIssueFSM;
        }

        /**
         * Sets the value of the dateIssueFSM property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateIssueFSM(XMLGregorianCalendar value) {
            this.dateIssueFSM = value;
        }

        /**
         * Gets the value of the terrOrganRAR property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public OrgInfoRusClaimIssue getTerrOrganRAR() {
            return terrOrganRAR;
        }

        /**
         * Sets the value of the terrOrganRAR property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public void setTerrOrganRAR(OrgInfoRusClaimIssue value) {
            this.terrOrganRAR = value;
        }

        /**
         * Gets the value of the declarer property.
         * 
         * @return
         *     possible object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public OrgInfoRusClaimIssue getDeclarer() {
            return declarer;
        }

        /**
         * Sets the value of the declarer property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrgInfoRusClaimIssue }
         *     
         */
        public void setDeclarer(OrgInfoRusClaimIssue value) {
            this.declarer = value;
        }

        /**
         * Gets the value of the comments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComments() {
            return comments;
        }

        /**
         * Sets the value of the comments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComments(String value) {
            this.comments = value;
        }

        /**
         * Gets the value of the signReference property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getSignReference() {
            return signReference;
        }

        /**
         * Sets the value of the signReference property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setSignReference(byte[] value) {
            this.signReference = value;
        }

        /**
         * Gets the value of the signCertificate property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getSignCertificate() {
            return signCertificate;
        }

        /**
         * Sets the value of the signCertificate property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setSignCertificate(byte[] value) {
            this.signCertificate = value;
        }

    }

}
