//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.clientref_v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Российские индивидуальные предприниматели
 * 
 * <p>Java class for FLType_ClaimIssue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FLType_ClaimIssue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ClientRegId" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="FullName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INN" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}INN12Type"/>
 *         &lt;element name="address_ur" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgUrAddressTypeULFL"/>
 *         &lt;element name="address" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgAddressTypeULFL"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FLType_ClaimIssue", propOrder = {

})
public class FLTypeClaimIssue {

    @XmlElement(name = "ClientRegId", required = true)
    protected String clientRegId;
    @XmlElement(name = "FullName", required = true)
    protected String fullName;
    @XmlElement(name = "INN", required = true, nillable = true)
    protected String inn;
    @XmlElement(name = "address_ur", required = true)
    protected OrgUrAddressTypeULFL addressUr;
    @XmlElement(required = true)
    protected OrgAddressTypeULFL address;

    /**
     * Gets the value of the clientRegId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientRegId() {
        return clientRegId;
    }

    /**
     * Sets the value of the clientRegId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientRegId(String value) {
        this.clientRegId = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the addressUr property.
     * 
     * @return
     *     possible object is
     *     {@link OrgUrAddressTypeULFL }
     *     
     */
    public OrgUrAddressTypeULFL getAddressUr() {
        return addressUr;
    }

    /**
     * Sets the value of the addressUr property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgUrAddressTypeULFL }
     *     
     */
    public void setAddressUr(OrgUrAddressTypeULFL value) {
        this.addressUr = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link OrgAddressTypeULFL }
     *     
     */
    public OrgAddressTypeULFL getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgAddressTypeULFL }
     *     
     */
    public void setAddress(OrgAddressTypeULFL value) {
        this.address = value;
    }

}
