//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.notificationsbeginningturnover;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.fsrar.wegais.productref_v2.WbUnitType;


/**
 * Уведомление о начале оборота АП
 * 
 * <p>Java class for NotificationsBeginningTurnoverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationsBeginningTurnoverType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType" minOccurs="0"/>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="NUMBER" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="Date" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="LicenseRegNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *                   &lt;element name="Notifier" type="{http://fsrar.ru/WEGAIS/Common}FSRARIDType"/>
 *                   &lt;element name="Producer" type="{http://fsrar.ru/WEGAIS/Common}FSRARIDType"/>
 *                   &lt;element name="FullName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FullNameManufacturerLanguage" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AlcVolumeMin" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AlcVolumeMax" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AlcVolume" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="UnitType" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}WbUnitType"/>
 *                   &lt;element name="PackageType" type="{http://fsrar.ru/WEGAIS/Common}packageTypeString" minOccurs="0"/>
 *                   &lt;element name="Capacity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType" minOccurs="0"/>
 *                   &lt;element name="DistinctiveCharacteristics" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ShelfLife" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeIntegerType"/>
 *                   &lt;element name="StorageTemperatureMin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="StorageTemperatureMax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="StorageHumidityMin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="StorageHumidityMax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="OtherStorageCharacteristics" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CodAP231" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="CodOKPD2" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="CodTNVEDTS" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="VidAP171FZ" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *                   &lt;element name="DateFirstDelivery" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
 *                   &lt;element name="TrademarkDetails" type="{http://fsrar.ru/WEGAIS/Common}BrandString" minOccurs="0"/>
 *                   &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TermsTransportation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TermsSale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="TermsDisposal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LabelFoto" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CompositionProducts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/NotificationsBeginningTurnover}PositionCompositionProductsType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IdentifyingDocuments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/NotificationsBeginningTurnover}PositionIdentifyingDocumentsType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Declaration">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/NotificationsBeginningTurnover}PositionDeclarationType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationsBeginningTurnoverType", propOrder = {
    "identity",
    "header",
    "compositionProducts",
    "identifyingDocuments",
    "declaration"
})
public class NotificationsBeginningTurnoverType {

    @XmlElement(name = "Identity")
    protected String identity;
    @XmlElement(name = "Header", required = true)
    protected NotificationsBeginningTurnoverType.Header header;
    @XmlElement(name = "CompositionProducts", required = true)
    protected NotificationsBeginningTurnoverType.CompositionProducts compositionProducts;
    @XmlElement(name = "IdentifyingDocuments", required = true)
    protected NotificationsBeginningTurnoverType.IdentifyingDocuments identifyingDocuments;
    @XmlElement(name = "Declaration", required = true)
    protected NotificationsBeginningTurnoverType.Declaration declaration;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationsBeginningTurnoverType.Header }
     *     
     */
    public NotificationsBeginningTurnoverType.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationsBeginningTurnoverType.Header }
     *     
     */
    public void setHeader(NotificationsBeginningTurnoverType.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the compositionProducts property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationsBeginningTurnoverType.CompositionProducts }
     *     
     */
    public NotificationsBeginningTurnoverType.CompositionProducts getCompositionProducts() {
        return compositionProducts;
    }

    /**
     * Sets the value of the compositionProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationsBeginningTurnoverType.CompositionProducts }
     *     
     */
    public void setCompositionProducts(NotificationsBeginningTurnoverType.CompositionProducts value) {
        this.compositionProducts = value;
    }

    /**
     * Gets the value of the identifyingDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationsBeginningTurnoverType.IdentifyingDocuments }
     *     
     */
    public NotificationsBeginningTurnoverType.IdentifyingDocuments getIdentifyingDocuments() {
        return identifyingDocuments;
    }

    /**
     * Sets the value of the identifyingDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationsBeginningTurnoverType.IdentifyingDocuments }
     *     
     */
    public void setIdentifyingDocuments(NotificationsBeginningTurnoverType.IdentifyingDocuments value) {
        this.identifyingDocuments = value;
    }

    /**
     * Gets the value of the declaration property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationsBeginningTurnoverType.Declaration }
     *     
     */
    public NotificationsBeginningTurnoverType.Declaration getDeclaration() {
        return declaration;
    }

    /**
     * Sets the value of the declaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationsBeginningTurnoverType.Declaration }
     *     
     */
    public void setDeclaration(NotificationsBeginningTurnoverType.Declaration value) {
        this.declaration = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/NotificationsBeginningTurnover}PositionCompositionProductsType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class CompositionProducts {

        @XmlElement(name = "Position")
        protected List<PositionCompositionProductsType> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PositionCompositionProductsType }
         * 
         * 
         */
        public List<PositionCompositionProductsType> getPosition() {
            if (position == null) {
                position = new ArrayList<PositionCompositionProductsType>();
            }
            return this.position;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/NotificationsBeginningTurnover}PositionDeclarationType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class Declaration {

        @XmlElement(name = "Position")
        protected List<PositionDeclarationType> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PositionDeclarationType }
         * 
         * 
         */
        public List<PositionDeclarationType> getPosition() {
            if (position == null) {
                position = new ArrayList<PositionDeclarationType>();
            }
            return this.position;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="NUMBER" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="Date" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="LicenseRegNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
     *         &lt;element name="Notifier" type="{http://fsrar.ru/WEGAIS/Common}FSRARIDType"/>
     *         &lt;element name="Producer" type="{http://fsrar.ru/WEGAIS/Common}FSRARIDType"/>
     *         &lt;element name="FullName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FullNameManufacturerLanguage" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AlcVolumeMin" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AlcVolumeMax" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AlcVolume" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="UnitType" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}WbUnitType"/>
     *         &lt;element name="PackageType" type="{http://fsrar.ru/WEGAIS/Common}packageTypeString" minOccurs="0"/>
     *         &lt;element name="Capacity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType" minOccurs="0"/>
     *         &lt;element name="DistinctiveCharacteristics" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ShelfLife" type="{http://fsrar.ru/WEGAIS/Common}NoNegativeIntegerType"/>
     *         &lt;element name="StorageTemperatureMin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="StorageTemperatureMax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="StorageHumidityMin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="StorageHumidityMax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="OtherStorageCharacteristics" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CodAP231" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="CodOKPD2" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="CodTNVEDTS" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="VidAP171FZ" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
     *         &lt;element name="DateFirstDelivery" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime"/>
     *         &lt;element name="TrademarkDetails" type="{http://fsrar.ru/WEGAIS/Common}BrandString" minOccurs="0"/>
     *         &lt;element name="Note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TermsTransportation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TermsSale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="TermsDisposal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LabelFoto" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Header {

        @XmlElement(name = "NUMBER", required = true)
        protected String number;
        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "LicenseRegNumber")
        protected String licenseRegNumber;
        @XmlElement(name = "Notifier", required = true)
        protected String notifier;
        @XmlElement(name = "Producer", required = true)
        protected String producer;
        @XmlElement(name = "FullName", required = true)
        protected String fullName;
        @XmlElement(name = "FullNameManufacturerLanguage")
        protected String fullNameManufacturerLanguage;
        @XmlElement(name = "AlcVolumeMin")
        protected BigDecimal alcVolumeMin;
        @XmlElement(name = "AlcVolumeMax")
        protected BigDecimal alcVolumeMax;
        @XmlElement(name = "AlcVolume")
        protected BigDecimal alcVolume;
        @XmlElement(name = "UnitType", required = true)
        @XmlSchemaType(name = "string")
        protected WbUnitType unitType;
        @XmlElement(name = "PackageType")
        protected String packageType;
        @XmlElement(name = "Capacity")
        protected BigDecimal capacity;
        @XmlElement(name = "DistinctiveCharacteristics")
        protected String distinctiveCharacteristics;
        @XmlElement(name = "ShelfLife", required = true)
        protected BigInteger shelfLife;
        @XmlElement(name = "StorageTemperatureMin", required = true)
        protected BigDecimal storageTemperatureMin;
        @XmlElement(name = "StorageTemperatureMax", required = true)
        protected BigDecimal storageTemperatureMax;
        @XmlElement(name = "StorageHumidityMin", required = true)
        protected BigDecimal storageHumidityMin;
        @XmlElement(name = "StorageHumidityMax", required = true)
        protected BigDecimal storageHumidityMax;
        @XmlElement(name = "OtherStorageCharacteristics")
        protected String otherStorageCharacteristics;
        @XmlElement(name = "CodAP231", required = true)
        protected String codAP231;
        @XmlElement(name = "CodOKPD2", required = true)
        protected String codOKPD2;
        @XmlElement(name = "CodTNVEDTS", required = true)
        protected String codTNVEDTS;
        @XmlElement(name = "VidAP171FZ", required = true)
        protected String vidAP171FZ;
        @XmlElement(name = "DateFirstDelivery", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dateFirstDelivery;
        @XmlElement(name = "TrademarkDetails")
        protected String trademarkDetails;
        @XmlElement(name = "Note")
        protected String note;
        @XmlElement(name = "TermsTransportation")
        protected String termsTransportation;
        @XmlElement(name = "TermsSale")
        protected String termsSale;
        @XmlElement(name = "TermsDisposal")
        protected String termsDisposal;
        @XmlElement(name = "LabelFoto")
        protected byte[] labelFoto;

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNUMBER() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNUMBER(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the licenseRegNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLicenseRegNumber() {
            return licenseRegNumber;
        }

        /**
         * Sets the value of the licenseRegNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLicenseRegNumber(String value) {
            this.licenseRegNumber = value;
        }

        /**
         * Gets the value of the notifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotifier() {
            return notifier;
        }

        /**
         * Sets the value of the notifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotifier(String value) {
            this.notifier = value;
        }

        /**
         * Gets the value of the producer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProducer() {
            return producer;
        }

        /**
         * Sets the value of the producer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProducer(String value) {
            this.producer = value;
        }

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the fullNameManufacturerLanguage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullNameManufacturerLanguage() {
            return fullNameManufacturerLanguage;
        }

        /**
         * Sets the value of the fullNameManufacturerLanguage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullNameManufacturerLanguage(String value) {
            this.fullNameManufacturerLanguage = value;
        }

        /**
         * Gets the value of the alcVolumeMin property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAlcVolumeMin() {
            return alcVolumeMin;
        }

        /**
         * Sets the value of the alcVolumeMin property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAlcVolumeMin(BigDecimal value) {
            this.alcVolumeMin = value;
        }

        /**
         * Gets the value of the alcVolumeMax property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAlcVolumeMax() {
            return alcVolumeMax;
        }

        /**
         * Sets the value of the alcVolumeMax property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAlcVolumeMax(BigDecimal value) {
            this.alcVolumeMax = value;
        }

        /**
         * Gets the value of the alcVolume property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAlcVolume() {
            return alcVolume;
        }

        /**
         * Sets the value of the alcVolume property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAlcVolume(BigDecimal value) {
            this.alcVolume = value;
        }

        /**
         * Gets the value of the unitType property.
         * 
         * @return
         *     possible object is
         *     {@link WbUnitType }
         *     
         */
        public WbUnitType getUnitType() {
            return unitType;
        }

        /**
         * Sets the value of the unitType property.
         * 
         * @param value
         *     allowed object is
         *     {@link WbUnitType }
         *     
         */
        public void setUnitType(WbUnitType value) {
            this.unitType = value;
        }

        /**
         * Gets the value of the packageType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackageType() {
            return packageType;
        }

        /**
         * Sets the value of the packageType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackageType(String value) {
            this.packageType = value;
        }

        /**
         * Gets the value of the capacity property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCapacity() {
            return capacity;
        }

        /**
         * Sets the value of the capacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCapacity(BigDecimal value) {
            this.capacity = value;
        }

        /**
         * Gets the value of the distinctiveCharacteristics property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDistinctiveCharacteristics() {
            return distinctiveCharacteristics;
        }

        /**
         * Sets the value of the distinctiveCharacteristics property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDistinctiveCharacteristics(String value) {
            this.distinctiveCharacteristics = value;
        }

        /**
         * Gets the value of the shelfLife property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getShelfLife() {
            return shelfLife;
        }

        /**
         * Sets the value of the shelfLife property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setShelfLife(BigInteger value) {
            this.shelfLife = value;
        }

        /**
         * Gets the value of the storageTemperatureMin property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getStorageTemperatureMin() {
            return storageTemperatureMin;
        }

        /**
         * Sets the value of the storageTemperatureMin property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setStorageTemperatureMin(BigDecimal value) {
            this.storageTemperatureMin = value;
        }

        /**
         * Gets the value of the storageTemperatureMax property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getStorageTemperatureMax() {
            return storageTemperatureMax;
        }

        /**
         * Sets the value of the storageTemperatureMax property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setStorageTemperatureMax(BigDecimal value) {
            this.storageTemperatureMax = value;
        }

        /**
         * Gets the value of the storageHumidityMin property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getStorageHumidityMin() {
            return storageHumidityMin;
        }

        /**
         * Sets the value of the storageHumidityMin property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setStorageHumidityMin(BigDecimal value) {
            this.storageHumidityMin = value;
        }

        /**
         * Gets the value of the storageHumidityMax property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getStorageHumidityMax() {
            return storageHumidityMax;
        }

        /**
         * Sets the value of the storageHumidityMax property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setStorageHumidityMax(BigDecimal value) {
            this.storageHumidityMax = value;
        }

        /**
         * Gets the value of the otherStorageCharacteristics property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOtherStorageCharacteristics() {
            return otherStorageCharacteristics;
        }

        /**
         * Sets the value of the otherStorageCharacteristics property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOtherStorageCharacteristics(String value) {
            this.otherStorageCharacteristics = value;
        }

        /**
         * Gets the value of the codAP231 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodAP231() {
            return codAP231;
        }

        /**
         * Sets the value of the codAP231 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodAP231(String value) {
            this.codAP231 = value;
        }

        /**
         * Gets the value of the codOKPD2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodOKPD2() {
            return codOKPD2;
        }

        /**
         * Sets the value of the codOKPD2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodOKPD2(String value) {
            this.codOKPD2 = value;
        }

        /**
         * Gets the value of the codTNVEDTS property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodTNVEDTS() {
            return codTNVEDTS;
        }

        /**
         * Sets the value of the codTNVEDTS property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodTNVEDTS(String value) {
            this.codTNVEDTS = value;
        }

        /**
         * Gets the value of the vidAP171FZ property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVidAP171FZ() {
            return vidAP171FZ;
        }

        /**
         * Sets the value of the vidAP171FZ property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVidAP171FZ(String value) {
            this.vidAP171FZ = value;
        }

        /**
         * Gets the value of the dateFirstDelivery property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDateFirstDelivery() {
            return dateFirstDelivery;
        }

        /**
         * Sets the value of the dateFirstDelivery property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDateFirstDelivery(XMLGregorianCalendar value) {
            this.dateFirstDelivery = value;
        }

        /**
         * Gets the value of the trademarkDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrademarkDetails() {
            return trademarkDetails;
        }

        /**
         * Sets the value of the trademarkDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrademarkDetails(String value) {
            this.trademarkDetails = value;
        }

        /**
         * Gets the value of the note property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNote() {
            return note;
        }

        /**
         * Sets the value of the note property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNote(String value) {
            this.note = value;
        }

        /**
         * Gets the value of the termsTransportation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermsTransportation() {
            return termsTransportation;
        }

        /**
         * Sets the value of the termsTransportation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermsTransportation(String value) {
            this.termsTransportation = value;
        }

        /**
         * Gets the value of the termsSale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermsSale() {
            return termsSale;
        }

        /**
         * Sets the value of the termsSale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermsSale(String value) {
            this.termsSale = value;
        }

        /**
         * Gets the value of the termsDisposal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermsDisposal() {
            return termsDisposal;
        }

        /**
         * Sets the value of the termsDisposal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermsDisposal(String value) {
            this.termsDisposal = value;
        }

        /**
         * Gets the value of the labelFoto property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getLabelFoto() {
            return labelFoto;
        }

        /**
         * Sets the value of the labelFoto property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setLabelFoto(byte[] value) {
            this.labelFoto = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Position" type="{http://fsrar.ru/WEGAIS/NotificationsBeginningTurnover}PositionIdentifyingDocumentsType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "position"
    })
    public static class IdentifyingDocuments {

        @XmlElement(name = "Position")
        protected List<PositionIdentifyingDocumentsType> position;

        /**
         * Gets the value of the position property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the position property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPosition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PositionIdentifyingDocumentsType }
         * 
         * 
         */
        public List<PositionIdentifyingDocumentsType> getPosition() {
            if (position == null) {
                position = new ArrayList<PositionIdentifyingDocumentsType>();
            }
            return this.position;
        }

    }

}
