//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.notificationsbeginningturnover;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ru.fsrar.wegais.productref_v2.DocumentVidType;


/**
 * Позиция
 * 
 * <p>Java class for PositionIdentifyingDocumentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionIdentifyingDocumentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType"/>
 *         &lt;element name="DocumentVid" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}DocumentVidType"/>
 *         &lt;element name="DocumentNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="ElectronicView" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionIdentifyingDocumentsType", propOrder = {

})
public class PositionIdentifyingDocumentsType {

    @XmlElement(name = "Identity", required = true)
    protected String identity;
    @XmlElement(name = "DocumentVid", required = true)
    @XmlSchemaType(name = "string")
    protected DocumentVidType documentVid;
    @XmlElement(name = "DocumentNumber", required = true)
    protected String documentNumber;
    @XmlElement(name = "ElectronicView")
    protected byte[] electronicView;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the documentVid property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentVidType }
     *     
     */
    public DocumentVidType getDocumentVid() {
        return documentVid;
    }

    /**
     * Sets the value of the documentVid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentVidType }
     *     
     */
    public void setDocumentVid(DocumentVidType value) {
        this.documentVid = value;
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the electronicView property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getElectronicView() {
        return electronicView;
    }

    /**
     * Sets the value of the electronicView property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setElectronicView(byte[] value) {
        this.electronicView = value;
    }

}
