//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.notificationsbeginningturnover;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.fsrar.wegais.productref_v2.DeclarationVidType;


/**
 * Позиция
 * 
 * <p>Java class for PositionDeclarationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionDeclarationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType"/>
 *         &lt;element name="DeclarationtVid" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}DeclarationVidType"/>
 *         &lt;element name="DeclarationNumber" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="DateValidity" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime" minOccurs="0"/>
 *         &lt;element name="DateExpiration" type="{http://fsrar.ru/WEGAIS/Common}DateNoTime" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionDeclarationType", propOrder = {

})
public class PositionDeclarationType {

    @XmlElement(name = "Identity", required = true)
    protected String identity;
    @XmlElement(name = "DeclarationtVid", required = true)
    @XmlSchemaType(name = "string")
    protected DeclarationVidType declarationtVid;
    @XmlElement(name = "DeclarationNumber", required = true)
    protected String declarationNumber;
    @XmlElement(name = "DateValidity")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateValidity;
    @XmlElement(name = "DateExpiration")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateExpiration;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the declarationtVid property.
     * 
     * @return
     *     possible object is
     *     {@link DeclarationVidType }
     *     
     */
    public DeclarationVidType getDeclarationtVid() {
        return declarationtVid;
    }

    /**
     * Sets the value of the declarationtVid property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclarationVidType }
     *     
     */
    public void setDeclarationtVid(DeclarationVidType value) {
        this.declarationtVid = value;
    }

    /**
     * Gets the value of the declarationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclarationNumber() {
        return declarationNumber;
    }

    /**
     * Sets the value of the declarationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclarationNumber(String value) {
        this.declarationNumber = value;
    }

    /**
     * Gets the value of the dateValidity property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateValidity() {
        return dateValidity;
    }

    /**
     * Sets the value of the dateValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateValidity(XMLGregorianCalendar value) {
        this.dateValidity = value;
    }

    /**
     * Gets the value of the dateExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateExpiration() {
        return dateExpiration;
    }

    /**
     * Sets the value of the dateExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateExpiration(XMLGregorianCalendar value) {
        this.dateExpiration = value;
    }

}
