//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.repproducedproduct_v4;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.repproducedproduct_v4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.repproducedproduct_v4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RepProducedTypeV4 }
     * 
     */
    public RepProducedTypeV4 createRepProducedTypeV4() {
        return new RepProducedTypeV4();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link UsedResourceType }
     * 
     */
    public UsedResourceType createUsedResourceType() {
        return new UsedResourceType();
    }

    /**
     * Create an instance of {@link RepProducedTypeV4 .Header }
     * 
     */
    public RepProducedTypeV4 .Header createRepProducedTypeV4Header() {
        return new RepProducedTypeV4 .Header();
    }

    /**
     * Create an instance of {@link RepProducedTypeV4 .Content }
     * 
     */
    public RepProducedTypeV4 .Content createRepProducedTypeV4Content() {
        return new RepProducedTypeV4 .Content();
    }

    /**
     * Create an instance of {@link RepProducedTypeV4 .ContentResource }
     * 
     */
    public RepProducedTypeV4 .ContentResource createRepProducedTypeV4ContentResource() {
        return new RepProducedTypeV4 .ContentResource();
    }

}
