//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.25 at 03:09:56 PM MSK 
//


package ru.fsrar.wegais.querygenerationopenkey;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * запрос на генерацию открытого ключа
 * 
 * <p>Java class for QueryGenerationOpenKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryGenerationOpenKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientId" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="CertificateRequest" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryGenerationOpenKeyType", propOrder = {
    "clientId",
    "certificateRequest"
})
public class QueryGenerationOpenKeyType {

    @XmlElement(name = "ClientId", required = true)
    protected String clientId;
    @XmlElement(name = "CertificateRequest", required = true)
    protected byte[] certificateRequest;

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the certificateRequest property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCertificateRequest() {
        return certificateRequest;
    }

    /**
     * Sets the value of the certificateRequest property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCertificateRequest(byte[] value) {
        this.certificateRequest = value;
    }

}
